language: ruby
rvm:
- 2.7.6
addons:
  chrome: stable
before_deploy:
- rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.0
deploy:
  provider: heroku
  app: afternoon-garden-82317
  run: bundle exec rails db:migrate
  skip_cleanup: true
  api_key:
    secure: FLjIsMzFhnHSHKJ3VjxPorQ6tYY+Lyj1EgsAEAaOqRDahiMqNR++4lIEZCVYJM53APrqdq9pUTxHRWUJNRcjzgRes959HPMHRQXZ7Tr+COS6tREjtEmX01jZxU+jHPGunRWuININzFOjAGYln3XnwDriC1ZkbCphBJ3cD6HnMvIS0KQrKOuQ5mc+l9Hzc6JRGc5VH///TjxshXJlSqmytYuAvWDL7HSXVr3S9ozcas4e7L/UOZo1JnGGrgRAkK4rb4ivqoyf+jCPOPkzmg79zEpe3vGnMSXIA7tbfB+OusQ9F77FtLa5NDjYZCvu9PHfzranqwPqJc/NlNigGHcBfCKeCvkn5bxrkFTv7KVZV+efGbfnCsDr83RCEgtHdKmMyd6Is70iQ+zLDd0WohNsIKb7dkWynvvm6UD7K1jFjc1e+80znMgkE2gYJIYA9nRL850+RZydM9sJyDtQHfGkigZRK6qy82p/qctvHcV6rxfL38URW8mfLpYzPl4w41Fq7ElXg/NsKIYdPd2iX7xtQCoKzQVUA3t9HmlG5+7oBtUqwrNXq/o+ra4TI3X8rk+vKNSPnv91XG/GadK/PWmJjvKqAxAqei0pgOzCViU1WO37W74UR5C9YZXGoyqsDH3fX4HTykhceLhhCkRBBun8gDlIW60ad6IBTDCE0NUC14E=
script:
- nvm install --lts
- bundle exec rails db:migrate
- bundle exec rails assets:precompile
- bundle exec rspec -fd spec
env:
  global:
    secure: Q4aNjr02tVHRSVOfXUFOnO4fZJq6i7K94ik0F56AFh8DyPB5U2N+T3SoKxSrYMuJjjRLoY3DA3cqOqYZfh8LebZfN5XmV+N1VBATp+hX0QQel218wvtLdiOu9o40vWwEa4hTRMVfdnUKOa85R74zEnjks6wRMg7P5e+AJGLEXO+LylI977D/jaNBk1wJ/vOYpdkObIuJzC/34GPJjX/CHUOMUt6w2wZr6bm+ynZs/0NCelN8HfX10sxabJuda7pG219gRMkc7JYqJtYLhSaJ8HWFg1gQ7i2Mc24j/xbK8j5y3NwS6PR2GnnLkT38pze3czhBj1xDY0DlBK76WghBExoVlJYALSmy0kfM0cDGhI6EjI7sy8WvLnGbzV+AyffzUXGsgwMRTJZtFnDBphZxdQ17BnGUaWRWw100Gym2ztrfpEupXvlzn3lqwFk+D6cJvqGCamGDzD0CVSvRv2ot7nBaua7VmNCkx6rN1FMuaZYj0HzLQU70ZinujNZrfHdUwbqGfyIOlXKpFQUk/hUBaErryTJgPZj54xuoqglX4vtuguB2FYfG7lOFx064OcXuVavqG0l//tYjtZ9LyAJxcIxKLSSAMUchrUhVuVweC559VnIvnm6u29CEpyy5kUh0nVZBUZEYx9bjtft3HlY5UR9aOq0+Yb/rkmM04dAlt/g=
